### ISSUE TITLE
Language Detector

### ISSUE THREAD

**Issue by hsuehpascal** [joshuaavalon/ChineseTranslationSimplifiedToTraditional#1]
Hi,

First of all thank you for this piece of great work. It works like magic and makes up for Google Translate's absence from Safari:)

Despite the script not having been updated for a while now I would like to ask if you could be so kind as to add the language code "zh-CN" to it as it currently doesn't work on some of the sites marked other than "zh-Hans". Or I would really appreciate it if anyone could point out to me how I can amend the language detection part for this to happen. Thanks in advance.

**Comment by joshuaavalon** [comment]
https://github.com/joshuaavalon/ChineseTranslationSimplifiedToTraditional/blob/268e229d70dbf423e8a740e901dfca46c9d8613b/main.js#L15-L16

This is the only part it does it. It relies on html tag having a correct language attribute. There isn't any good way to detect language of a piece of text except [Google Translate API](https://cloud.google.com/translate/docs/detecting-language) (Paid).

Also, the translate code is actually pretty bad. You may want to use [繁化姬](https://zhconvert.org/). However, its API limits that you cannot request it from cross origin. You may need a proxy server.
